
// testing connection to database
//GET http://localhost:5000/



// testing ports

//GET http://localhost:5000/api/firewall/ip


POST http://localhost:5000/api/firewall/ip/

{
    "values": ["192.168.1.1", "192.168.1.2"],
    "mode": "blacklist"
}

DELETE http://localhost:5000/api/firewall/ip/192.168.1.1
